abcxyz/team-link

- apis/v1alpha1/interface.go
- interface and method renaming
- method return changed because source team <-> github team is many to many
> fix: interface methods and names

- pkg/github/synchronizer.go
Tested, should be members. also see [members](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#organization-permissions-for-members)
> fix: github permission for synchronizer

- apis/v1alpha1/team_link.pb.go
- protos/v1alpha1/team_link.proto
Other references to a 'source' team id throughout this project represent the id a string. This change make the team id in the `SourceEvent` proto message consistent with that representation.
> Make `SourceEvent.team_id` a string

- apis/v1alpha3/interface.go
Add a more general interface that is agnostic to the Source Group System and the target group system.
> Add `v1alpha3` package

- pkg/groupsync/groups.go
- pkg/groupsync/manytomanysyncer.go
- pkg/groupsync/manytomanysyncer_test.go
* Add an implementation of the `GroupSyncer` interface for syncing groups that form a many to many relationship.
* Added structs and interfaces for manipulating a group system in a generalized way.
> Add Many to Many GroupSyncer

- pkg/groupsync/groups.go
There are times where you are only interested in the `Member`'s ID. This method allows accessing the ID without having to unwrap the `Member` to its underlying type.
> Add `ID` convenience memthod to `Member`.

- pkg/groupsync/manytomanysyncer_test.go
This makes each method have  consistent behavior.
> Add locking to other methods of testGroupReadWriter

- pkg/groupsync/manytomanysyncer.go
- pkg/groupsync/manytomanysyncer_test.go
Right now teamlink tries continue syncing what it can if an error occurs. This leads to unexpected behavior under certain error conditions and instead we should just fail fast and abort the sync entirely if an error occurs. All `logger.Warn` statements have been switched to `logger.Error` statements to reflect this change.
> Abort sync if an error occurrs

- pkg/groupsync/manytomanysyncer.go
Remove call to lookup user from target sytem from `ManyToManySyncer`. `ManyToManySyncer` can just pass in the IDs of the users to the target system `GroupWriter` which can decide itself if it needs to lookup any information aside from the ID.
This change will help eliminate unnecessary calls and therefore reduce rate limiting errors.
> Reduce calls

- pkg/github/teamreadwriter.go
Clean up the `SetMembers` function by spliting out the different scenarios (add/remove user/subteam) into their own functions
Add configuration option to enable inviting the user to the org being synced to if they are not already a member.
> Refactor `SetMembers`

- pkg/github/teamreadwriter.go
- pkg/github/teamreadwriter_test.go
We were forgetting to return errors adding/removing team members in `SetMembers`.
> Bugfix - return error in SetMembers for GitHub

- pkg/client/mapper.go
- pkg/client/mapper_test.go
This PR includes:
1. Create `GroupMapper` type for `GoogleGroup->GitHub` and `GitHub->GoogleGroup` mappers.
2. Update Mapper constructor to create both mapper mentioned above.
Kudos to @drevell for pair programming and come up with this clean and elegant solution.
> feat: create mapper from github to google groups

- .github/minty.yaml
Follow up for https://github.com/abcxyz/team-link/pull/97
> fix: update minty to only allow main branch trigger

- .github/workflows/sync.yml
We can also make this a cron job, but so far we are not actively using this, we can add this cron job thing later if needed.
> Update sync workflow to be only manual trigger

- .github/minty.yaml
Changing minty config to allow token request on non-main branch so I can test on getting SSO identity during development
> Update minty config to allow calling on non-main branch

- pkg/common/googlegroup_github/mapper_test.go
- pkg/utils/textproto_test.go
This is no longer required as of Go 1.22
> Remove shadowed loop variables

- .github/minty.yaml
Update minty rule to allow development on  branch`sailorlqh/sso_poc` to be able to request tokens.
The `sso_poc` branch will be used to test graphQL to obtain user SAML identities.
> update minty rule to allow dev

- .github/minty.yaml
According to this link: https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#create-an-installation-access-token-for-an-app.
`member: write` permission gives us permission to sync members and read org members.
Also I am so dumb so I made a typo in previous commit 😭
> fix: fix minty permissions

- .github/minty.yaml
`create-tag` workflow will be included in the followup PR
> update minty to allow create tag

- .github/workflows/ci.yml
This allows release workflow to call ci workflow.
> fix: add workflow_call trigger to ci workflow

- go.mod
- go.sum
- pkg/github/client.go
- pkg/github/sso.go
- pkg/github/teamreadwriter.go
- pkg/github/teamreadwriter_test.go
This PR implement feature of checking if user has SSO enabled before adding the user to github group.
The procedure of doing this is:
1. Use GraphQL to Get all SAML identities within the given org.
2. When adding users to github team, check if the given team requires SSO and if this user has saml identity in the organization.
This feature is tested in my test org with mapping a same google group to two different github team with one requires SSO and the other one don't.
Team that requires SSO only added member with saml identity. While the doesn't require SSO added all team member.
> feat: add SSO support for github

- pkg/common/googlegroup_github/mapper.go
- pkg/gitlab/access_level.go
- pkg/gitlab/groupreadwriter.go
- pkg/gitlab/groupreadwriter_test.go
- pkg/groupsync/groups.go
- pkg/groupsync/manytomanysyncer.go
- pkg/groupsync/manytomanysyncer_test.go
* Add concept of Mappings with metadata 
* Combine mapping metadata per-user for all source groups mapping to a given target group
* Use metadata to calculate access level for users in GitLab groups
Will be paired with changes in the G3 side of teamlink to populate access level metadata in GitLab group mappings, defaulting to Developer access.
> Calculate access level for gitlab users

- pkg/github/client.go
- pkg/github/sso.go
Change GetAllOrgsSamlIdentities to take a httpclient instead of a staticTokenSource makes the caller to be more versatile instead of bounded to use staticTokenSource
> fix: refactor SSO functions to accept httpclient

- pkg/github/client.go
- pkg/github/sso.go
- pkg/github/teamreadwriter.go
- pkg/github/teamreadwriter_test.go
This PR will be helpful for our internal development as internally, teamlink is hosted as a service, we can't only initialize the SAML identity when service started.
Feature contained in this PR includes:
1. Update GitHub's `TeamReadWriter` with a `endpoint` field. This is usefully for creating graphql client to get saml identities.
2. Change `orgSamlIdentities` into a cache. Thus if teamlink is running as a service, saml can be updated.
> Refactor to use cache for SAML identity

- go.mod
- go.sum
- pkg/github/client.go
- pkg/github/pagination.go
- pkg/github/sso.go
- pkg/github/teamreadwriter.go
- pkg/github/teamreadwriter_test.go
to match what we use internally, also v67 has new feature to manipulate org role which will be needed in the subsequent prs.
> chore: bump go-github version

- pkg/groupsync/manytomanysyncer_test.go
these error variables are accessible in the groupsync package which could cause confusions since they are only errors used in tests.  We cannot prefix the variables since lint complaints naming should start with "err".
> chore: remove pkg wide variable for testing

- pkg/github/scim.go
- pkg/github/scim_test.go
Create our own SCIM client, this is required for teamlink to provision users in enterprise server, The github lib provides a scim client for enterprise cloud not for server, see https://github.com/google/go-github/blob/master/github/scim.go and https://docs.github.com/en/enterprise-cloud@latest/rest/scim?apiVersion=2022-11-28, the apis are different than what is for server.
> feat: implement scim client

- pkg/github/enterpriseuserwriter.go
- pkg/github/enterpriseuserwriter_test.go
- pkg/github/scim.go
This allows the SCIM provisioner to manage the roles granted to users over time. Previously, roles would be added on user creation but never updated or removed.
> feat: Support role updates and removals in EnterpriseUserWriter

- go.mod
- pkg/groupsync/manytoonesyncer.go
- pkg/groupsync/manytoonesyncer_test.go
- pkg/groupsync/util.go
In ManyToOne, the unit of work is based on the target groups, not the source groups. The previous implementation kicked off concurrent processing based on each known source group, which would cause the same target groups to be handled multiple times.
---
Also update to Go 1.25 to take advantage of the newly added `waitgroup.Go()` in stdlib.
> feat: Reduce work done for ManyToOne SyncAll
