abcxyz/team-link

pkg/github/synchronizer.go, pkg/github/synchronizer_test.go
#18 
It is a bug during testing where login is missing in an invitation and caused the program to panic.
=> fix missing github user login in invitation

pkg/github/pagination.go, pkg/github/synchronizer.go
=> Add pagination helper

pkg/groupsync/groups.go
Using recursion could result in stack overflow style errors if the group being procesed has a large depth. A BFS traversal avoids this issue.
=> Update `Descendants` function to use BFS traversal

pkg/groupsync/groups.go
small adjustments to help code readability.
=> tweak for readability

pkg/groupsync/manytomanysyncer.go, pkg/groupsync/manytomanysyncer_test.go, pkg/groupsync/util.go, pkg/groupsync/util_test.go
=> Use concurrency in `ManyToManySyncer.SyncAll`.

pkg/github/teamreadwriter.go
We do not expect user or group information to change frequently so we can enable caching to help prevent rate limiting by GitHub. Note we do not cache calls to `GetMembers` as we always want membership information to be as fresh as possible.
=> Add caching to `GetUser` and `GetGroup`.

pkg/github/teamreadwriter.go, pkg/groupsync/manytomanysyncer.go
* Only log out user IDs as other information just creates noise.
* Make `SetMembers` more inormative by logging which members are being added/removed
=> Refine logging statements

pkg/github/teamreadwriter.go, pkg/github/teamreadwriter_test.go
TeamLink was incorrectly adding and removing the same users as it was treating usernames in a case-senstive manner.
=> fix: Treat usernames in a case-insensitive manner

pkg/github/teamreadwriter.go
=> Simplify set construction and comparison

pkg/github/teamreadwriter.go
Add configuration option to enable inviting the user to the org being synced to if they are not already a member.
=> Add toggle to invite a user to the org

pkg/credentials/keyprovider.go, pkg/github/tokensource.go, pkg/gitlab/client.go, pkg/gitlab/groupreadwriter.go, pkg/gitlab/groupreadwriter_test.go
https://github.com/abcxyz/team-link/issues/70
=> Add GitLab client provider to support dynamic credentials fetching

.github/minty.yaml
=> remove todo

pkg/client/mapper.go, pkg/googlegroups/groupreader.go
These fixes were included in https://github.com/abcxyz/team-link/pull/82/files. That PR won't be merged this we will use another implementation method. Thus, those fixes will be included here.
=> fix: fix typo and small bugs

pkg/gitlab/client.go
Unfortunately there's no existing ClientOptionFunc for this in the gitlab client library
=> Support custom user agent in gitlab client

.github/minty.yaml
=> Revert "Update minty config to allow calling on non-main branch"

pkg/gitlab/access_level.go, pkg/gitlab/groupreadwriter.go
We will want to be able to set different access levels for members of GitLab groups.
=> Support different access levels for GitLab groups

.github/workflows/sync.yml
=> Update from mint-token to minty action

.github/workflows/ci.yml, .github/workflows/create-tag.yml
Update to use the new actions repo for actions instead of pkg.
=> chore: use new actions repo

pkg/github/metadata.go, pkg/github/orgmembershipreadwriter.go, pkg/github/orgmembershipreadwriter_test.go
Addressing Dave's post-merge comments from https://github.com/abcxyz/team-link/pull/141
=> chore: Readability fixes in org membership read/writer

pkg/github/tokensource.go
=> chore: add constructor for signer provider

pkg/github/enterpriseuserwriter.go, pkg/github/enterpriseuserwriter_test.go, pkg/github/scim.go, pkg/github/scim_test.go
Provision user accounts via SCIM API
=> feat: enterpriseuserreadwriter that manages ghes user accounts

pkg/github/enterpriseuserwriter.go
tmp fix: deactivate before reactivate
=> tmp fix: deactivate before reactivate
